Style:
  Font: 'sans' # sans (Inter), serif (Lora), mono (JetBrains Mono)
  Borders: false
  Radius: true
  AvatarShape: 'circle' # circle, square, rounded
  DefaultMode: 'light' # light / dark

Colors:
  Primary: '#0ddeb0'
  Highlight: '#0ddeb0'
  Background: '#fff'
  Body: '#232323'
  Light: '#fefefe'

Content:
  Name: 'Jane Doe'
  Bio: 'Your new favourite person'
  Avatar: 'default2.webp'

Links:
  'My project': 'https://myproject.me.com'
  'My videos': 'https://youtube.com'

Social:
  Linkedin: 'https://linkedin.com/'
  Mastodon: 'https://mastodon.social'
  Bluesky: ''
  Threads: ''
  Twitter: ''
  Instagram: 'https://instagram.com'
  Snapchat: ''
  Facebook: 'https://facebook.com'
  Vimeo: ''
  YouTube: ''
  TikTok: ''
  Twitch: ''
  Spotify: ''
  GitHub: 'https://github.com'
  GitLab: ''
  StackOverflow: ''
  Discord: ''
  Behance: ''
  Dribble: ''
  Reddit: ''
  Quora: ''
  Substack: 'https://substack.com/'
  Medium: ''
  WordPress: ''
  WhatsApp: ''
  Telegram: ''
  Strava: ''
  Custom: 'https://customlink.domain'

Footer:
  Text: 'No cookies, no forms, and no data collection.'
